import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/headers'
import Tech from '../components/custom/Technologies'
import Portfolio from '../components/custom/WorkSamples'
import Reviews from '../components/custom/Reviews'
import Contact from '../components/custom/Contact'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="root-header">
        <Header />
        <Tech />
        <Portfolio />
        <Reviews />
        <Contact />
      </div>
    </div>
  )
}
